const SystemConstants = {
    EXAMPLE_SEQ_FILE            : "ATTCGGTGGCCGGTGGTGCCAACCGTG\n" + 
                                    "AAAAGATAGATAGACACAGATAGATAGACACAGTAGAGAGAGATGAGACACACAGATGAGAGATAG\n" + 
                                    "AAACACAGGTAGAGGAGAGGATTAGGAGAGATGACAGATAGACCCCGCGCTCGCGTCGCTCGCGCTCTCCCCCCTTGGCTCACAGAC\n" + 
                                    "AGAGACCGCTGGATGACAGATAGATAGACCCCCAGATAGATAAAGGGGTAGATAGATAGATAGAGGACAGTA\n" + 
                                    "ACAGATTGAGAGTGGCACACGTGGGACACCACAGTTTGTAGATCGATAG\n" + 
                                    "ACGTGCCAGTAGACGTGAAAGTAGACAGATAGATGGAGATAGAC\n",
    STATUS_CARREGAMENTO         : {STARTED: 'STARTED', FAILED: 'FAILED', FINISHED: 'FINISHED'},
}

export default SystemConstants;