const SystemConstants = {
    exampleSeqFile                : "ATTCGGTGGCCGGTGGTGCCAACCGTG\n" + 
                                    "AAAAGATAGATAGACACAGATAGATAGACACAGTAGAGAGAGATGAGACACACAGATGAGAGATAG\n" + 
                                    "AAACACAGGTAGAGGAGAGGATTAGGAGAGATGACAGATAGACCCCGCGCTCGCGTCGCTCGCGCTCTCCCCCCTTGGCTCACAGAC\n" + 
                                    "AGAGACCGCTGGATGACAGATAGATAGACCCCCAGATAGATAAAGGGGTAGATAGATAGATAGAGGACAGTA\n" + 
                                    "ACAGATTGAGAGTGGCACACGTGGGACACCACAGTTTGTAGATCGATAG\n" + 
                                    "ACGTGCCAGTAGACGTGAAAGTAGACAGATAGATGGAGATAGAC\n"
}

export default SystemConstants;